import { Flex, Heading } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Menu } from '@components/Menu'

const Home: NextPage = () => {
  return (
    <Flex>
      <Head>
        <title>Nick Rameau's Den | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
    </Flex>
  )
}

export default Home
